name: 'Free Code Coverage - UPDATE'
description: 'Update code coverage data when pull request is labeled, unlabeled, and closed'
inputs:
  bucket-name:
    description: 'S3 bucket name to be used to persist code coverage data between runs.'
    required: true
  project-name:
    description:
      "Lower kebab case string (lower-kebab-case-string) allowing to store action's data from multiple
      projects/repositories without collisions in the same bucket."
    required: true
  bypass-label:
    description:
      'Label to be added to a pull request in order to bypass code coverage check.
      This label might be useful to knowingly accept a decrease in coverage.
      Make sure that if a custom value is used for the UPLOAD part, it is the same value provided here.'
    required: false
    default: 'ignoreCoverage'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucket-name }}
    - ${{ inputs.project-name }}
    - ${{ inputs.bypass-label }}
