on:
  pull_request:
    types: [labeled, unlabeled, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-name: [bypass-label, coverage-report, failure, no-previous-coverage-metric, success, valid]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./sync
        with:
          bucket-name: free-code-coverage
          project-name: ${{ matrix.project-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
