on:
  pull_request:
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-name: [bypass-label-embedded, failure-embedded, success-embedded]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./update-embedded
        with:
          bucket-name: free-code-coverage
          project-name: ${{ matrix.project-name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
