on: [pull_request]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./push
        with:
          bucket-name: someBucketName
